import { useState } from "react";
import { UserSubscription } from "../types";

interface Props {
  userSubs: UserSubscription[];
  totalMonthly: number;
  potentialSavings: number;
}

export default function SavingsReport({ userSubs, totalMonthly, potentialSavings }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const lines = [
      "📊 My Subscription Report (via SubSwap)",
      "═══════════════════════════════════",
      "",
      ...userSubs.map(
        (u) =>
          `• ${u.sub.name.padEnd(24)} $${u.price.toFixed(2)}/mo${
            u.sub.alternatives.filter((a) => a.price.startsWith("Free")).length > 0
              ? `  →  Free alternative: ${u.sub.alternatives.find((a) => a.price.startsWith("Free"))?.name}`
              : ""
          }`
      ),
      "",
      "─────────────────────────────────────",
      `Total monthly spend:   $${totalMonthly.toFixed(2)}`,
      `Total yearly spend:    $${(totalMonthly * 12).toFixed(2)}`,
      `Potential savings:     $${potentialSavings.toFixed(2)}/mo (if all switched to free)`,
      "",
      "Generated by SubSwap · https://subswap.app",
    ];

    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <button
      onClick={handleCopy}
      className={`flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold transition-all duration-200 ${
        copied
          ? "border-green-500/30 bg-green-500/20 text-green-300"
          : "border-white/20 bg-white/10 text-white/80 hover:border-violet-400/30 hover:text-violet-300 hover:bg-violet-500/10"
      }`}
    >
      {copied ? (
        <>
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" />
          </svg>
          Copy Report
        </>
      )}
    </button>
  );
}
